name: Lighting
on: [pull_request, workflow_dispatch]
jobs:
  build:
    name: Lighting
    runs-on: ubuntu-latest
    steps:
      - name: Update Lights
        env:
          IFTTT_URL: ${{ secrets.TOGGLE_IFTTT_HUE_GO }}
        run: python 'python/update_lights.py'
